### PR TITLE
Update Daughter cards with new arduino classes

### PR DESCRIPTION
**Pull request by mlecriva**

### CODE REVIEW

**Comment by thomasmevel** [comment]
On a fait les test:
-nouveau code server + nouveau code esp32 (erreur)
-nouveau code server + ancien code esp32 (erreur)
-ancien code server + ancien code esp32 (fonctionne)

**Comment by Enderdead** [comment]
This is an extract from the esp32 serial. That looks like the watchdog is triggered by this new feature.

`E (10282) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:\r\nE (10282) task_wdt:  - IDLE0 (CPU 0)\r\nE (10282) task_wdt: Tasks currently running:\r\nE (10282) task_wdt: CPU 0: Task_Manager\r\nE (10282) task_wdt: CPU 1: loopTask\r\nE (10282) task_wdt: Aorting.\r\naort() was 
`

**Comment by mlecriva** [comment]
> On a fait les test:
> -nouveau code server + nouveau code esp32 (erreur)
> -nouveau code server + ancien code esp32 (erreur)
> -ancien code server + ancien code esp32 (fonctionne)
-----
> This is an extract from the esp32 serial. That looks like the watchdog is triggered by this new feature.
> 
> `E (10282) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:\r\nE (10282) task_wdt: - IDLE0 (CPU 0)\r\nE (10282) task_wdt: Tasks currently running:\r\nE (10282) task_wdt: CPU 0: Task_Manager\r\nE (10282) task_wdt: CPU 1: loopTask\r\nE (10282) task_wdt: Aorting.\r\naort() was`
-----
@thomasmevel @Enderdead 

Bad news :/

Can you specify which version corresponds to the new esp32 code? 
Is it a version of the wheeledbase with SerialTopics?

Did you use the same esp32 to perform those tests?

**Comment by mlecriva** [comment]
#21 This issue explain why the last commit take place

**Pull request merged**
